### PR TITLE
New "codefresh" theme

### PR DESCRIPTION
**Pull request by tgolen**
@Razielt77 Sorry, I have been pushing to my own fork :( Sorry about that. Here is a PR into the master branch of the main repo.

### CODE REVIEW

**Comment by tgolen** [comment]
I added the mailchimp form stuff to this PR

**Comment by Razielt77** [comment]
cool.. I have installed it locally to try it out.. but I dont have admin credentials to login. any idea?

**Comment by tgolen** [comment]
When I looked in the DB there was an account for you and Tony. Since I didn't know the password, I made this edit in `core/server/models/user.js`

image

That will let you use "tony@codefresh.io" and anything for a password.

**Comment by Razielt77** [comment]
Hi I tried few times to log into admin with tony@codefresh.io and many passwords and couldn't get in. 

I am running it using:
npm install
grunt init
npm start

Do I need to run anything else?

**Pull request merged**
